const data = {
    products:[
        {
            _id: '1',
            name: 'Soft Sweater',
            category: 'J',
            image: '/images/p1.jpg', 
            price: 120,
            brand: 'Ecuador', 
            rating: 4.5, 
            numReviews: 10,
            description: 'Good quality jacket',
        },
        {
            _id: '2',
            name: 'Soft Pant Black',
            category: 'P',
            image: '/images/p2.jpg', 
            price: 110,
            brand: 'Ecuador', 
            rating: 4.4, 
            numReviews: 15,
            description: 'Good quality pants',
        },
        {
            _id: '3',
            name: 'Soft Pant Red',
            category: 'P',
            image: '/images/p3.jpg', 
            price: 130,
            brand: 'Ecuador', 
            rating: 4.6, 
            numReviews: 20,
            description: 'Good quality pants',
        },
        {
            _id: '4',
            name: 'Soft T-Shirt White',
            category: 'T-S',
            image: '/images/p4.jpg', 
            price: 90,
            brand: 'Ecuador', 
            rating: 4.3, 
            numReviews: 14,
            description: 'Good quality t-shirts',
        },
        {
            _id: '5',
            name: 'Soft T-Shirt black',
            category: 'T-S',
            image: '/images/p5.jpg', 
            price: 40,
            brand: 'Ecuador', 
            rating: 4.2, 
            numReviews: 13,
            description: 'Good quality t-shirt',
        },
        {
            _id: '6',
            name: 'Flag Bracelet',
            category: 'B',
            image: '/images/p6.jpg', 
            price: 11,
            brand: 'Ecuador', 
            rating: 4.1, 
            numReviews: 17,
            description: 'Good quality bracelet',
        },
        {
            _id: '7',
            name: 'Metal  Bracelet',
            category: 'B',
            image: '/images/p7.jpg', 
            price: 15,
            brand: 'Ecuador', 
            rating: 3.8, 
            numReviews: 35,
            description: 'Metal bracelet with Ecuador flag',
        },
    ]
}
export default data;